pub const NOISE_DIRS: &[&str] = &[
    "node_modules",
    ".git",
    "target",
    "__pycache__",
    ".next",
    "dist",
    "build",
    ".cache",
    ".turbo",
    ".vercel",
    ".pytest_cache",
    ".mypy_cache",
    ".tox",
    ".venv",
    "venv",
    "env",
    ".env",
    "coverage",
    ".nyc_output",
    ".DS_Store",
    "Thumbs.db",
    ".idea",
    ".vscode",
    ".vs",
    "*.egg-info",
    ".eggs",
    // Build tool caches
    ".gradle",
    ".cargo",
    ".npm",
    ".yarn",
    ".pnpm-store",
    // Vendor directories
    "vendor",
    // IaC / framework caches
    ".terraform",
    ".angular",
    ".svelte-kit",
    ".nuxt",
    // Test snapshots
    "__snapshots__",
];
