//! Vibe-specific configuration generation for Mistral Vibe hooks.
//!
//! This module provides TOML serialization for Vibe's hooks.toml configuration file.

use serde::Serialize;

/// A single hook configuration entry for Mistral Vibe
#[derive(Serialize)]
pub struct VibeHook {
    pub name: &'static str,
    #[serde(rename = "type")]
    pub hook_type: &'static str,
    #[serde(rename = "match")]
    pub match_: &'static str,
    pub command: String,
    pub timeout: f64,
    pub strict: bool,
    pub description: &'static str,
}

/// Root configuration for Mistral Vibe hooks.toml
#[derive(Serialize)]
pub struct VibeHooksConfig {
    pub hooks: Vec<VibeHook>,
}

/// Generate the hooks.toml content with the given hook script path
pub fn format_hooks_toml(hook_script_path: &str) -> String {
    let hooks = vec![
        VibeHook {
            name: "rtk-rewrite",
            hook_type: "pre_tool",
            match_: "bash",
            command: hook_script_path.to_string(),
            timeout: 60.0,
            strict: false,
            description: "Rewrite bash commands to use RTK for 60-90% token savings",
        },
        VibeHook {
            name: "rtk-rewrite-shell",
            hook_type: "pre_tool",
            match_: "run_shell_command",
            command: hook_script_path.to_string(),
            timeout: 60.0,
            strict: false,
            description: "Rewrite shell commands to use RTK for 60-90% token savings",
        },
    ];

    let config = VibeHooksConfig { hooks };

    format!(
        "# RTK hook configuration for Mistral Vibe\n# Auto-generated by rtk init --agent vibe\n\n{}",
        toml::to_string(&config).expect("Failed to serialize Vibe hooks config to TOML")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_hooks_toml_generates_valid_toml() {
        let result = format_hooks_toml("/path/to/rtk-hook-vibe.sh");

        // Verify header comments are present
        assert!(result.contains("# RTK hook configuration for Mistral Vibe"));
        assert!(result.contains("# Auto-generated by rtk init --agent vibe"));

        // Verify TOML structure - use flexible matching
        assert!(result.contains("[[hooks]]"));
        assert!(result.contains("rtk-rewrite"));
        assert!(result.contains("rtk-rewrite-shell"));
        assert!(result.contains("pre_tool"));
        assert!(result.contains("bash"));
        assert!(result.contains("run_shell_command"));
        assert!(result.contains("/path/to/rtk-hook-vibe.sh"));
        assert!(result.contains("timeout"));
        assert!(result.contains("strict"));
    }

    #[test]
    fn test_format_hooks_toml_escapes_special_characters() {
        // Path with spaces and special characters
        let path = "/path/with spaces/and-dashes/rtk-hook-vibe.sh";
        let result = format_hooks_toml(path);

        // TOML should contain the full path
        assert!(result.contains(path));
    }

    #[test]
    fn test_format_hooks_toml_uses_absolute_paths() {
        let result = format_hooks_toml("/absolute/path/to/hook.sh");

        // Should contain the absolute path
        assert!(result.contains("/absolute/path/to/hook.sh"));
    }

    #[test]
    fn test_vibe_hook_struct_serialization() {
        let hook = VibeHook {
            name: "test-hook",
            hook_type: "pre_tool",
            match_: "bash",
            command: "/test/command".to_string(),
            timeout: 30.0,
            strict: true,
            description: "Test description",
        };

        let toml = toml::to_string(&hook).unwrap();

        // Verify all fields are present (order may vary)
        assert!(toml.contains("test-hook"));
        assert!(toml.contains("pre_tool"));
        assert!(toml.contains("bash"));
        assert!(toml.contains("/test/command"));
        assert!(toml.contains("30") || toml.contains("30.0"));
        assert!(toml.contains("true"));
        assert!(toml.contains("Test description"));
    }

    #[test]
    fn test_vibe_hooks_config_serialization() {
        let hooks = vec![
            VibeHook {
                name: "hook1",
                hook_type: "pre_tool",
                match_: "bash",
                command: "/cmd1".to_string(),
                timeout: 60.0,
                strict: false,
                description: "Desc 1",
            },
            VibeHook {
                name: "hook2",
                hook_type: "pre_tool",
                match_: "run_shell_command",
                command: "/cmd2".to_string(),
                timeout: 60.0,
                strict: false,
                description: "Desc 2",
            },
        ];

        let config = VibeHooksConfig { hooks };
        let toml = toml::to_string(&config).unwrap();

        assert!(toml.contains("[[hooks]]"));
        assert!(toml.contains("hook1"));
        assert!(toml.contains("hook2"));
    }

    #[test]
    fn test_vibe_hooks_config_structure() {
        let result = format_hooks_toml("/test/path");

        // Verify the output can be parsed back as valid TOML
        // This ensures we're generating valid TOML syntax
        let _: toml::Value = result.parse().expect("Generated TOML should be valid");
    }
}
